### ISSUE TITLE
Error when running Install-Package libboost -Source "C:\hypepool\build\vcpkg" in VS

### ISSUE THREAD

**Issue by mja1175** [bonesoul/hypepool#12]
Any ideas what I'm missing?

PM> Install-Package libboost -Source "C:\hypepool\build\vcpkg"
Restoring packages for C:\hypepool\src\Blockchains\Monero\Monero.csproj...
  GET https://api.nuget.org/v3-flatcontainer/libboost/index.json
  NotFound https://api.nuget.org/v3-flatcontainer/libboost/index.json 157ms
Install-Package : Unable to find package libboost. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages, nuget.org
At line:1 char:1
+ Install-Package libboost -Source "C:\hypepool\build\vcpkg"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Install-Package : Package restore failed. Rolling back package changes for 'Monero'.
At line:1 char:1
+ Install-Package libboost -Source "C:\hypepool\build\vcpkg"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Time Elapsed: 00:00:00.5525383

**Comment by bonesoul** [comment]
No need to install libboost-package.

**Comment by mja1175** [comment]
Ok, thank you. This was just at the end of the grunt cook-deps  call

Exporting package boost:x86-windows... done
Creating nuget package...
Creating nuget package... done
NuGet package exported at: C:/hypepool/build/vcpkg/libboost.nupkg

With a project open, go to Tools->NuGet Package Manager->Package Manager Console and paste:
    Install-Package libboost -Source "C:\hypepool\build\vcpkg"

**Comment by mja1175** [comment]
I have some questions, is this thread the best way to communicate?

**Comment by bonesoul** [comment]
Sure go on please.

grunt cook-deps is just for future stuff (for updating hashing libraries for windows when needed).

**Comment by mja1175** [comment]
I started by creating a pool with CoiniumServ, I have it running for the most part but am stuck. I've added a new coin and added the new algo, everything connects and it even says it breaks blocks, but every block is rejected to 'high-hash'. I have no idea whats wrong. I pulled your new pool software to see if it would work better, I have everything pulled and built but don't really know where to go from here to get it functioning. I love what you've done and really want to get this working. I'm more than happy to pay for help at this point.

**Comment by bonesoul** [comment]
The new software is still in active development, so not production ready yet. Need a bit more work here.

**Comment by bonesoul** [comment]
closing this for now.

**Comment by bonesoul** [comment]
meanwhile tracking #9 for a fix.
