### ISSUE TITLE
Starting Pool

### ISSUE THREAD

**Issue by Dradden** [bonesoul/hypepool#29]
Grabbed HypePool this morning intending to play around with it, but am unable to start it. Is it currently able to start or does it still need some work? Seems I am missing a needed .dll (Hypepool.Cli.dll?)

**Comment by rumplin** [comment]
Works perfectly fine for me. Build and Start. Make sure Hypepool.Cli is your startup project.

**Comment by Dradden** [comment]
Can you give me an example of how you are starting it? This is a bit foreign to me, I normally deal in Linux, so a bit of a learning curve using Windows...

**Comment by rumplin** [comment]
Right click on the Hypepool.Cli project in Visual Studio, and select "Set as StartUp Project" then press F5 (start debug mode).

**Comment by bonesoul** [comment]
yes exactly so but we are still not production ready yet :)
