### ISSUE TITLE
pool dont start. i use win 10

### ISSUE THREAD

**Issue by pfreak2000** [bonesoul/hypepool#30]
Copyright (C) 2013 - 2018, hypepool project - Hüseyin Uslu
 https://github.com/bonesoul/hypepool

 hypepool comes with ABSOLUTELY NO WARRANTY.

 You can contribute the development of the project by donating;
 ETH : 0x61aa3e0709e20bcb4aedc2607d4070f1db72e69b

19:05:02 [INF] [Program] [-] hypepool warming-up: v0.0.1
19:05:02 [INF] [Program] [-] running on win-x64
19:05:02 [INF] [Program] [-] os: Microsoft Windows 10.0.16299
19:05:02 [INF] [Program] [-] dotnet core: 2.0.5, framework: .NET Core 4.6.26020.03
19:05:02 [INF] [Program] [-] running over 8 core system
19:05:02 [INF] [Engine] [-] starting engine..
19:05:02 [INF] [MoneroPool] [-] initializing pool..
19:05:02 [FTL] [MoneroPool] [-] Es wurde versucht, eine Datei mit einem falschen Format zu laden. (Exception from HRESULT: 0x8007000B)
19:05:02 [INF] [StratumServer] [pool-name] stratum server [127.0.0.1:3333] started..

**Comment by rumplin** [comment]
This project is still under development.

**Comment by pfreak2000** [comment]
so it dont work ?
nobody can start the pool ?

**Comment by bonesoul** [comment]
still not ready..
