### ISSUE TITLE
How configured this server?

### ISSUE THREAD

**Issue by dmshel** [bonesoul/hypepool#47]
Where config files?:))

**Comment by bonesoul** [comment]
still under development & not production ready, so basically you can't atm.

**Comment by dmshel** [comment]
i can do beta testman))))

**Comment by dmshel** [comment]
del

**Comment by rumplin** [comment]
@dmshel What part of "product not ready" did you not understand?

**Comment by dmshel** [comment]
@MokraCota tnx for ur comment. waiting when be ready

**Comment by bonesoul** [comment]
sorry, had a typo there; should be 'production ready'
